# Run all tests and builds all aspects of GWT using Java 11, 17, and 21. Runs
# nightly (plus or minus timzeones) on the main branch, and will also run right
# away on a push to a release branch. Release zips are uploaded as part of the
# build, though maven snapshots are not yet deployed.
name: Full build
on:
  push:
    # Build on pushes to main and release branches. For forks, the -test may
    # be helpful to run tests when preparing a merge.
    branches:
      - 'main'
      - 'release/*'
      - '*-test'
      - 'issue-7987-compatibility-with-issue-9584'
      - 'issue-7987-gwt-2.12.2'
  workflow_dispatch:
    # Allow running manually
  pull_request:
    types: [ labeled, synchronize ]
permissions:
  # allow publishing JUnit report for PRs
  checks: write 
jobs:
  build:
    if: ${{ !github.event.pull_request || contains(github.event.pull_request.labels.*.name, 'ready') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '11' ] #[ '17', '21', '22' ]
        java-distribution: [ 'temurin' ] #, 'sapmachine' ]
    steps:
      - name: Checkout GWT itself into one directory
        uses: actions/checkout@v5
        with:
          path: 'gwt'
      - name: Checkout GWT tools into a sibling directory
        uses: actions/checkout@v5
        with:
          repository: 'gwtproject/tools'
          path: 'tools'
      - name: Set up JDK ${{ matrix.java-version }}
        # GWT requires Java 11+ to build
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}

      - name: Build, style/api checks, test, produce docs
        run: |
          set -eux
          cd gwt
          java -version
          ant -version
          # Set env vars to ensure we get the build/test we expect
          export \
            TZ=America/Los_Angeles \
            ANT_OPTS='-Dfile.encoding=UTF8 -Xmx2g' \
            GWT_VERSION=2.12.2
          # Run the ant tasks, disabling watchFileChanges to work around a github actions limitation
          ant clean test dist doc \
            -Dgwt.version=${GWT_VERSION} \
            -Dtest.jvmargs='-ea -Dgwt.watchFileChanges=false' \
            -Dtest.web.htmlunit.disable=true \
            -Dtest.nometa.htmlunit.disable=true \
            -Dtest.emma.htmlunit.disable=true

      - name: Report test results
        uses: mikepenz/action-junit-report@v6.0.0
        if: always()
        with:
          report_paths: 'gwt/build/out/**/test/**/reports/TEST-*.xml'
      - name: Upload checkstyle xml for manual review in its own artifact
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: checkstyle-reports-${{ matrix.java-version }}-${{ matrix.java-distribution }}
          path: 'gwt/build/out/**/checkstyle*.xml'
      - name: Upload test xml files for manual review in its own artifact
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: junit-reports-java${{ matrix.java-version }}-${{ matrix.java-distribution }}
          path: 'gwt/build/out/**/test/**/reports/TEST-*.xml'

      - name: Determine release name
        run: echo "RELEASE_NAME=$( find gwt/build/dist/ -name 'gwt-*.zip' | sed -e 's/^.*\/gwt-\(.*\)\.zip$/\1/' )" >> "$GITHUB_ENV"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: gwt-${{ env.RELEASE_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release ZIP
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: gwt/build/dist/gwt-${{ env.RELEASE_NAME }}.zip
          asset_name: gwt-${{ env.RELEASE_NAME }}.zip
          asset_content_type: application/x-zip

      - name: On success, upload the release zip
        uses: actions/upload-artifact@v5
        with:
          name: gwt-${{ matrix.java-version }}-${{ matrix.java-distribution }}
          path: 'gwt/build/dist/gwt-*.zip'

      - name: Set up sonatype credentials
        # Using the same java version as above, set up a settings.xml file
        uses: actions/setup-java@v5
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && github.repository_owner == 'gwtproject' && matrix.java-version == '21' }}
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
          # Define the ID for the server to put in settings.xml, and the env vars that will contain the secrets
          server-id: sonatype-snapshots
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD

      - name: Nightly builds should be deployed as snapshots to sonatype
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' && github.repository_owner == 'gwtproject' && matrix.java-version == '21' }}
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          set -eux
          # Set the version to deploy (it was also set in the build step above)
          export GWT_VERSION=2.12.2
          export GWT_MAVEN_REPO_URL=https://central.sonatype.com/repository/maven-snapshots/
          export GWT_MAVEN_REPO_ID=sonatype-snapshots
          cd gwt
          # With no user input, run the push-gwtproject.sh script to deploy org.gwtproject artifacts
          maven/push-gwtproject.sh < /dev/null
